import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import "./globals.css";
import Link from "next/link";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <header className="fixed top-0 p-3 flex justify-between items-center w-screen h-12 bg-slate-400">
        <div>logo</div>
        <nav className="flex justify-between">
          <Link href="/posts" className="pr-3">
            posts
          </Link>
          <Link href="/portfolio" className="pr-3">
            portfolio
          </Link>
          <Link href="/resume">resume</Link>
        </nav>
      </header>
      <body className="mt-12">{children}</body>
    </html>
  );
}
