name: Cypress Tests
on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Yarn 3
        run: npm install -g yarn@3.0

      - name: Install Dependencies
        run: yarn install

      - name: Cypress run
        run: |
          yarn build
          yarn start
